language: ruby
rvm:
- 2.6.2
sudo: false
addons:
  postgresql: '9.3'
branches:
  only:
  - master
  - develop
bundler_args: "--without production --jobs=3"
cache: bundler
before_install:
- gem update --system
- gem update bundler
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database-travis.yml config/database.yml
- bundle exec rake db:schema:load RAILS_ENV=test
deploy:
  provider: heroku
  api_key:
    secure: jmZjV6+9yhdtXHp35lVsfKn9hN2SPKSW4qU69vj1w53X8KdZE8xuykW+tyTF/XosiKobk2lmV0y2u176u/P9IL1TEsINLOBZ9IZwbkiPOyw+nuBXC8EKzs8CDKUtX4aXRape3mJrTHV3ibGqUQ50AKrDsgbYaO0xafYRMmhIDeo=
  app:
    develop: engineerssg-staging
    master: murmuring-shore-8908
  on:
    repo: engineersftw/website
  run: rake db:migrate
notifications:
  slack: teamtechladies:ps1NAx9fspD4RJobMG9vg2NE
